Add Minio Helm Chart
CSCfi/helm-charts pull request #5
Opened 2023-12-15 12:22 UTC by trispera

2024-01-09 08:59 UTC, lvarin commented on charts/minio/templates/NOTES.txt
> +  export MINIO=$(oc get route --namespace={{ .Release.Namespace }} -o yaml | yq '.items[1].spec.host')
```suggestion
  export MINIO=$(oc get route --namespace={{ .Release.Namespace }} -o yaml | yq '.items[] | select(.metadata.name == "{{ .Values.minio.clusterName }}-console") .spec.host´ -r)
```

2024-01-10 06:21 UTC, trispera commented on charts/minio/Chart.yaml
> +appVersion: "1.16.0"
It's the default version generated by the command `helm create ...`

2024-01-10 07:15 UTC, lvarin requested changes
Check the requested changes

2024-01-10 12:39 UTC, trispera commented on charts/minio/templates/NOTES.txt
> +  export MINIO=$(oc get route --namespace={{ .Release.Namespace }} -o yaml | yq '.items[1].spec.host')
Tested and approved

2024-01-10 13:37 UTC, lvarin approved these changes

2024-01-10 13:37 UTC, merged